apiVersion: v1
kind: Service
metadata:
  name: product-api-service-node
spec:
  type: LoadBalancer
  selector:
    app: product-api-node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30002
